title: James Green
logo: /assets/img/profile_4.png
description: "A commercial research manager with 6 years of experience working with data"
             "Always working to grow technical skills and implement to solve real-world problems."
show_downloads: False
theme: jekyll-theme-minimal
