title: James Green
logo: /assets/img/profile_4.png
description: "A commericial research manager with 6 years experinece working with data looking to move more formally into Data Science"
show_downloads: False
theme: jekyll-theme-minimal
