title: James Green
logo: /assets/img/profile_4.png
description: |   
  Always working to grow and implement technical skills to solve real-world problems.
show_downloads: False
theme: jekyll-theme-minimal
